version: '3'
services:
    httpd:
        image: fholzer/nginx-brotli:v1.19.1
        volumes:
            - ./build:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 12366:80